// ponytail: a static list instead of a lookup API — it never covers
// everything a user might type, but it doesn't need to: free text stays
// allowed, and n8n validates the actual recipe request afterwards.
/** Common ingredient names offered by the autocomplete while typing. */
export const INGREDIENT_SUGGESTIONS: string[] = [
  'Apple',
  'Asparagus',
  'Avocado',
  'Bacon',
  'Baby spinach',
  'Banana',
  'Basil',
  'Bay leaf',
  'Beef',
  'Bell pepper',
  'Black beans',
  'Black pepper',
  'Broccoli',
  'Brown rice',
  'Butter',
  'Cabbage',
  'Carrot',
  'Cauliflower',
  'Celery',
  'Cheddar cheese',
  'Cherry tomatoes',
  'Chicken breast',
  'Chicken thigh',
  'Chickpeas',
  'Chili powder',
  'Chives',
  'Cilantro',
  'Cinnamon',
  'Coconut milk',
  'Cod',
  'Coriander',
  'Corn',
  'Cottage cheese',
  'Cream cheese',
  'Cucumber',
  'Cumin',
  'Dill',
  'Egg',
  'Feta cheese',
  'Fish sauce',
  'Flour',
  'Garlic',
  'Ginger',
  'Green beans',
  'Ground beef',
  'Ham',
  'Heavy cream',
  'Honey',
  'Kale',
  'Ketchup',
  'Kidney beans',
  'Lamb',
  'Leek',
  'Lemon',
  'Lentils',
  'Lettuce',
  'Lime',
  'Mango',
  'Maple syrup',
  'Mayonnaise',
  'Milk',
  'Mint',
  'Mozzarella',
  'Mushroom',
  'Mustard',
  'Noodles',
  'Nutmeg',
  'Oats',
  'Olive oil',
  'Onion',
  'Oregano',
  'Paprika',
  'Parmesan',
  'Parsley',
  // Deliberately out of alphabetical order: matches the "Pas" autocomplete
  // order shown in the step 1 Figma reference (Pasta, Pastrami, Passion fruit).
  'Pasta',
  'Pastrami',
  'Passion fruit',
  'Peanut butter',
  'Peas',
  'Pineapple',
  'Pork',
  'Potato',
  'Pumpkin',
  'Quinoa',
  'Radish',
  'Red onion',
  'Rice',
  'Rosemary',
  'Salmon',
  'Salt',
  'Sausage',
  'Sesame oil',
  'Shallot',
  'Shrimp',
  'Soy sauce',
  'Spinach',
  'Spring onion',
  'Sugar',
  'Sweet potato',
  'Thyme',
  'Tofu',
  'Tomato',
  'Tortilla',
  'Tuna',
  'Turkey',
  'Turmeric',
  'Vanilla',
  'Vinegar',
  'Walnut',
  'Yogurt',
  'Zucchini',
];
