// ponytail: a static list instead of a lookup API — it never covers
// everything a user might type, but it doesn't need to: free text stays
// allowed, and n8n validates the actual recipe request afterwards.
/** Common ingredient names offered by the autocomplete while typing. */
export const INGREDIENT_SUGGESTIONS: string[] = [
  'Almonds',
  'Anchovies',
  'Apple',
  'Asparagus',
  'Avocado',
  'Baby spinach',
  'Bacon',
  'Baguette',
  'Banana',
  'Barley',
  'Basil',
  'Bay leaf',
  'Beef',
  'Beetroot',
  'Bell pepper',
  'Black beans',
  'Black pepper',
  'Bread',
  'Breadcrumbs',
  'Broccoli',
  'Brown rice',
  'Brussels sprouts',
  'Bulgur',
  'Butter',
  'Cabbage',
  'Capers',
  'Carrot',
  'Cashews',
  'Cauliflower',
  'Celery',
  'Cheddar cheese',
  'Cheese',
  'Cherry tomatoes',
  'Chicken',
  'Chicken breast',
  'Chicken thigh',
  'Chickpeas',
  'Chili',
  'Chili powder',
  'Chives',
  'Cilantro',
  'Cinnamon',
  'Coconut milk',
  'Cod',
  'Coriander',
  'Corn',
  'Cottage cheese',
  'Couscous',
  'Crab',
  'Cream',
  'Cream cheese',
  'Cucumber',
  'Cumin',
  'Dill',
  'Duck',
  'Egg',
  'Eggplant',
  'Feta cheese',
  'Fish',
  'Fish sauce',
  'Flour',
  'Garlic',
  'Ginger',
  'Gouda',
  'Green beans',
  'Ground beef',
  'Haddock',
  'Halibut',
  'Ham',
  'Heavy cream',
  'Herring',
  'Honey',
  'Kale',
  'Ketchup',
  'Kidney beans',
  'Lamb',
  'Leek',
  'Lemon',
  'Lentils',
  'Lettuce',
  'Lime',
  'Lobster',
  'Mackerel',
  'Mango',
  'Maple syrup',
  'Mayonnaise',
  'Milk',
  'Mint',
  'Mozzarella',
  'Mushroom',
  'Mussels',
  'Mustard',
  'Noodles',
  'Nutmeg',
  'Oats',
  'Olive oil',
  'Olives',
  'Onion',
  'Oregano',
  'Paprika',
  'Parmesan',
  'Parsley',
  // Deliberately out of alphabetical order: matches the "Pas" autocomplete
  // order shown in the step 1 Figma reference (Pasta, Pastrami, Passion fruit).
  'Pasta',
  'Pastrami',
  'Passion fruit',
  'Peanut butter',
  'Pear',
  'Peas',
  'Pineapple',
  'Pita bread',
  'Pollock',
  'Pork',
  'Potato',
  'Prawns',
  'Protein powder',
  'Pumpkin',
  'Quinoa',
  'Radish',
  'Red onion',
  'Rice',
  'Ricotta',
  'Rosemary',
  'Rye bread',
  'Salami',
  'Salmon',
  'Salt',
  'Sardines',
  'Sausage',
  'Scallops',
  'Sea bass',
  'Sesame oil',
  'Shallot',
  'Shrimp',
  'Sour cream',
  'Sourdough bread',
  'Soy sauce',
  'Spinach',
  'Spring onion',
  'Squid',
  'Strawberries',
  'Sugar',
  'Sweet potato',
  'Thyme',
  'Tilapia',
  'Toast',
  'Tofu',
  'Tomato',
  'Tortilla',
  'Trout',
  'Tuna',
  'Turkey',
  'Turmeric',
  'Vanilla',
  'Vinegar',
  'Walnut',
  'Whey protein',
  'White fish',
  'Whole wheat bread',
  'Yeast',
  'Yogurt',
  'Zucchini',
];
